# **Introduction to SVD**

It In this notebook, you will practice your understanding of SVD by applying it to several matrices and exploring the result.

## **SVD: Theoretical Reminder**

Singular Value Decomposition (SVD) is a highlight of Linear Algebra. It allows one to decompose *any* rectangular matrix $A$ into a product of three matrices, namely **orthogonal** matrices $U$ and $V$ and a **diagonal** matrix $\Sigma$ as follows: 

<center>$A = U\Sigma V^T$</center>

Such a decomposition makes subsequent computations easier and is important for many applications.

The diagonal values $\sigma_{i}$ in the $\Sigma$ matrix are known as the singular values of the original matrix $A$, while the columns of the $U$ and $V$ matrices, $u_i$'s and $v_i$'s, are left anf right singular vectors of $A$ respectively.

From the decomposition above it follows that the following relationship should hold between the singular values and the singular vectors:

<center>$Av_i = \sigma_i u_i$</center>

But how do we find those $u$'s, $v$'s and $\sigma$'s?

It turns out that the left singular vectors $u_1, ..., u_r$ are actually the eigenvectors of $AA^T$ that correspond to its non-zero eigenvalues, while the right singular vectors $v1, ..., v_r$ are the eigenvectors corresponding to the non-zero eigenvaluesof $A^TA$.

Finally, $A$'s singular values  $\sigma_i^2$ are the non-zero eigenvalues of both $A^TA$ and $AA^T$ *(see the lecture notes for a proof of why they are the same)*.

## **SVD in Action: Toy Example**

Luckily, SVD is already implemented in Python, and you will not need re-implement it from scratch ourselves. 

Instead, let's define a toy matrix, decompose it with a built-in function and carefully explore the result.

**Run the cells below one-by-one, accasionally filling in the code where needed.**

In [121]:
import numpy as np

In [122]:
A = np.array([[3,4,3],
              [1,2,3],
              [4,2,1]])

Now, apply SVD to the data we've just loaded.

*Hint:* The SVD can be calculated by calling the [$\texttt{svd()}$](https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html) function from the $\texttt{linalg}$ module of the $\texttt{numpy}$ library.



In [123]:
# Your code here
svd = np.linalg.svd
svd(A)

(array([[-0.73553325, -0.18392937, -0.65204358],
        [-0.42657919, -0.62196982,  0.65664582],
        [-0.52632788,  0.76113306,  0.37901904]]),
 array([7.87764972, 2.54031671, 0.69958986]),
 array([[-0.60151068, -0.61540527, -0.5093734 ],
        [ 0.73643349, -0.18005275, -0.65210944],
        [ 0.30959751, -0.76737042,  0.5615087 ]]))

In [124]:
u, s, vh = svd(A)
u @ np.diag(s) @ vh

array([[3., 4., 3.],
       [1., 2., 3.],
       [4., 2., 1.]])

Let's explore the output of the function. 

How many singular values does $A$ have?

In [125]:
len(s)

3

What are the dimensions of the matrices $U$ and $V$.

In [126]:
print(f'U: {u.shape}; V: {vh.shape}')

U: (3, 3); V: (3, 3)


Now, double-check that the decomposition actually works, i.e. check that $A = U\Sigma V^T$:

In [127]:
u @ np.diag(s) @ vh

array([[3., 4., 3.],
       [1., 2., 3.],
       [4., 2., 1.]])

We've said before that the column vectors of the matrices $U$ and $V$ are the eigenvectors of $AA^T$ and $A^TA$ respectively, while $\sigma_i^2$ are the corresponding eigenvalues. Double-check that that's indeed the case.

In [128]:
s ** 2

array([62.05736504,  6.45320899,  0.48942597])

In [129]:
np.linalg.eigvalsh(A.T @ A)

array([ 0.48942597,  6.45320899, 62.05736504])

In [130]:
np.linalg.eigvalsh(A @ A.T)

array([ 0.48942597,  6.45320899, 62.05736504])

In [131]:
u

array([[-0.73553325, -0.18392937, -0.65204358],
       [-0.42657919, -0.62196982,  0.65664582],
       [-0.52632788,  0.76113306,  0.37901904]])

In [132]:
np.linalg.eigh(A @ A.T)[0]

array([ 0.48942597,  6.45320899, 62.05736504])

In [133]:
vh

array([[-0.60151068, -0.61540527, -0.5093734 ],
       [ 0.73643349, -0.18005275, -0.65210944],
       [ 0.30959751, -0.76737042,  0.5615087 ]])

In [134]:
np.linalg.eigh(A.T @ A)[1].T

array([[ 0.30959751, -0.76737042,  0.5615087 ],
       [-0.73643349,  0.18005275,  0.65210944],
       [-0.60151068, -0.61540527, -0.5093734 ]])

Double-chek that $U$ and $V$ are orthogonal matrices (e.g., show that $UU^T = U^TU = E$)

In [135]:
u @ u.T

array([[1.00000000e+00, 2.60871289e-16, 2.43540025e-16],
       [2.60871289e-16, 1.00000000e+00, 9.93060877e-17],
       [2.43540025e-16, 9.93060877e-17, 1.00000000e+00]])

In [136]:
u.T @ u

array([[ 1.00000000e+00,  1.80398578e-17, -3.58082693e-17],
       [ 1.80398578e-17,  1.00000000e+00, -1.52945536e-17],
       [-3.58082693e-17, -1.52945536e-17,  1.00000000e+00]])

Finally, check that the relationship between the estimated singular vectors and singular values of $A$ is as follows: $Av_i = \sigma_i u_i$.

In [137]:
s

array([7.87764972, 2.54031671, 0.69958986])

In [138]:
A @ np.linalg.eigh(A)[1]

array([[-0.2171052 , -2.08851605, -5.4397579 ],
       [ 1.36562477, -1.20516729, -3.26843094],
       [-1.88649199,  0.059887  , -4.17583064]])

In [139]:
np.diag(s) @ u

array([[-5.7942733 , -1.44893113, -5.13657089],
       [-1.08364623, -1.58000033,  1.66808836],
       [-0.36821365,  0.53248097,  0.26515788]])

In [140]:
for uu, vv, ss in zip(u.T, vh, s):
  print('A*vi = ', A@vv)
  print('s_i*u_i', ss*uu)
  print('\n')

A*vi =  [-5.7942733  -3.3604414  -4.14622666]
s_i*u_i [-5.7942733  -3.3604414  -4.14622666]


A*vi =  [-0.46723885 -1.58000033  1.93351902]
s_i*u_i [-0.46723885 -1.58000033  1.93351902]


A*vi =  [-0.45616307  0.45938276  0.26515788]
s_i*u_i [-0.45616307  0.45938276  0.26515788]




## **SVD on the Iris Dataset**

Now, we'll apply SVD on the famous iris dataset.


In [73]:
from sklearn.datasets import load_iris
from sklearn.decomposition import TruncatedSVD

iris = load_iris()
B = iris.data

Let's take a look at the first 10 examples:

In [74]:
B[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

Now, apply SVD to the dataset:

In [75]:
svd(B)

(array([[-0.06161685,  0.12961144,  0.0021386 , ..., -0.09343429,
         -0.09573864, -0.08085465],
        [-0.05807094,  0.11101978,  0.07067239, ...,  0.03690405,
         -0.03153954,  0.01309526],
        [-0.05676305,  0.11796647,  0.00434255, ...,  0.03066199,
          0.19531473,  0.13569909],
        ...,
        [-0.0940593 , -0.0498297 , -0.04144001, ...,  0.98181631,
         -0.02194514, -0.00894446],
        [-0.09488961, -0.05610123, -0.21297821, ..., -0.02155617,
          0.94178018, -0.02971961],
        [-0.08847836, -0.0515697 , -0.09575285, ..., -0.0086052 ,
         -0.03021088,  0.9736599 ]]),
 array([95.95991387, 17.76103366,  3.46093093,  1.88482631]),
 array([[-0.75110816, -0.38008617, -0.51300886, -0.16790754],
        [ 0.2841749 ,  0.5467445 , -0.70866455, -0.34367081],
        [ 0.50215472, -0.67524332, -0.05916621, -0.53701625],
        [ 0.32081425, -0.31725607, -0.48074507,  0.75187165]]))

In [76]:
u1, s1, vh1 = svd(B)

Explore the dimensions of the matrices $U$ and $V$ and the number of singular values of the data matrix, $r$. 

In [81]:
print(f'U: {u1.shape}; V: {vh1.shape}')

U: (150, 150); V: (4, 4)


"Trim" the matrices $U$ and $V$ returned by $\texttt{np.svd()}$ to get rid of redundant dimensions. 

You should get $A_{m\times n} = U_{m\times r}\Sigma_{r\times r} V_{n\times r}^T$, where $r$ is the number of singular values of the data matrix $A$.

In [86]:
u2 = u1[:4,:]

In [89]:
B2 = u1[:,:4] @ np.diag(s1) @ vh1
B2[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

Imagine that we want to use only two factors in the latent representation of the data. How would the approximated data look like?

In [99]:
B3 = u1[:,:2] @ np.diag(s1[:2]) @ vh1[:2,:]
B3[:10]

array([[5.0952927 , 3.50597743, 1.40192232, 0.20165319],
       [4.74588049, 3.19610853, 1.46136967, 0.25800276],
       [4.68667405, 3.21586325, 1.30954904, 0.19452725],
       [4.61488457, 3.08894388, 1.46347879, 0.27002699],
       [5.07488651, 3.50623125, 1.36428119, 0.1863997 ],
       [5.52598407, 3.7330351 , 1.67566825, 0.28872322],
       [4.731593  , 3.2288014 , 1.36216771, 0.21446447],
       [5.00510918, 3.39830515, 1.47931372, 0.24418439],
       [4.37933538, 2.93134058, 1.38864652, 0.25618379],
       [4.80551481, 3.23360903, 1.48569239, 0.26393296]])