In [1]:
import numpy as np

# Problem 1

In [ ]:
A = np.array([
              [1, 2, 1],
              [-1, -2, 1],
              [2, 4, 2]
])

In [ ]:
np.linalg.matrix_rank(A)

2

# Problem 2

Find the straight line y = w_1*x + w_0 that is the best least-squares fit to the points (0,0), (1,3) and (2,7).

### Solution

The general formula for the leasr squares solution is the following:

(X.T * X) ^ (-1) * X.T * Y

In [ ]:
X = np.array([
              [0, 1, 2],
              [1, 1, 1]
              ]).T
y = np.array([0, 3, 7])

In [ ]:
X

array([[0, 1],
       [1, 1],
       [2, 1]])

In [ ]:
y

array([0, 3, 7])

In [ ]:
inv = np.linalg.inv

In [ ]:
w = inv(X.T @ X) @ X.T @ y
w

array([ 3.5       , -0.16666667])

Thus, the straight line is **y = 3.5x - 1/6**

### Let's check it!

In [ ]:
w1, w0 = np.linalg.lstsq(X, y, rcond=None)[0]
w1, w0

(3.5, -0.16666666666666646)

# Problem 3

DiagonalizeAor show explain why this is not possible.

In [ ]:
A = np.array([
              [4, 0, 0, 0],
              [0, 2, 0, 0],
              [0, 0, 4, 0],
              [1, 0, 0, 2]
])

In [ ]:
# Manually calculated, steps 2-4
S = np.array([
              [2, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 1, 0],
              [1, 0, 0, 1]
])

In [ ]:
Sinv = inv(S)
Sinv

array([[ 0.5,  0. ,  0. ,  0. ],
       [ 0. ,  1. ,  0. ,  0. ],
       [ 0. ,  0. ,  1. ,  0. ],
       [-0.5,  0. ,  0. ,  1. ]])

In [ ]:
inv(S) @ A @ S

array([[4., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 4., 0.],
       [0., 0., 0., 2.]])

### Check

In [ ]:
A = np.array([
              [4, 0, 0, 0],
              [0, 2, 0, 0],
              [0, 0, 4, 0],
              [1, 0, 0, 2]
])

In [ ]:
eigvals, eigvecs = np.linalg.eig(A)

In [ ]:
eigvals

array([2., 4., 2., 4.])

In [ ]:
eigvecs

array([[0.        , 0.89442719, 0.        , 0.        ],
       [0.        , 0.        , 1.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        ],
       [1.        , 0.4472136 , 0.        , 0.        ]])

In [ ]:
inv(eigvecs)

array([[-0.5       ,  0.        ,  0.        ,  1.        ],
       [ 1.11803399,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ]])

In [ ]:
inv(eigvecs) @ A @ eigvecs

array([[2., 0., 0., 0.],
       [0., 4., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 4.]])

In [ ]:
np.diag(eigvals)

array([[2., 0., 0., 0.],
       [0., 4., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 4.]])

In [ ]:
inv(eigvecs) @ A @ eigvecs == np.diag(eigvals)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

# EXAM

In [2]:
A = np.array([
              [3,4,-2],
              [1,4,-1],
              [2,6,-1]
])

v = np.array([1,1,2])

In [5]:
A @ v

array([3, 3, 6])

In [12]:
u = np.array([0,10,0])
v = np.array([0,3,3])

In [8]:
np.linalg.norm(u, 2)

10.0

In [9]:
np.linalg.norm(v, 2)

4.242640687119285

In [15]:
u @ v / (np.linalg.norm(u, 2) * np.linalg.norm(v, 2))

0.7071067811865476

In [16]:
1/np.sqrt(2)

0.7071067811865475

In [18]:
a = np.array([[1,1],[1,1]])
a @ np.array([[5,0],[0,0.5]])

array([[5. , 0.5],
       [5. , 0.5]])

In [19]:
A = np.array([[1,2],[3,4]])
B = np.array([[4,3],[2,1]])
C = np.array([[1,1],[1,1]])

In [20]:
B@(A@C)

array([[33, 33],
       [13, 13]])

In [21]:
(B@A)@C

array([[33, 33],
       [13, 13]])

In [22]:
B@A

array([[13, 20],
       [ 5,  8]])

In [23]:
4*3^4-2*3^3-12*3^2

47

In [29]:
a = np.array([3,2,-1])
b = np.array([4,0,3])

a@b / np.linalg.norm(b)

1.8

In [30]:
np.linalg.eig(np.array([[0,-1],[-1,0]]))

(array([ 1., -1.]), array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))

## Problem 1

## Problem 2

## Problem 3

## Problem 4

## Problem 5

## Problem 6